# Generated by Django 3.2 on 2023-06-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RewardsRadar', '0004_customer_square_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='square_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
