# Generated by Django 3.2 on 2023-06-02 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RewardsRadar', '0005_alter_customer_square_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_transaction_id', models.CharField(max_length=255)),
                ('reward_points', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RewardsRadar.customer')),
            ],
        ),
    ]
