# Generated by Django 3.2 on 2023-06-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RewardsRadar', '0008_auto_20230605_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='square_subscription_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
